server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    user-online:
      topic: ${KAFKA_USER_ONLINE_TOPIC:user-online}
      group: ${KAFKA_USER_ONLINE_GROUP:user-online-message-service}
    delete-encrypt-keys:
      topic: ${KAFKA_DELETE_ENCRYPT_KEYS_TOPIC:delete-encrypt-keys}
      group: ${KAFKA_DELETE_ENCRYPT_KEYS_GROUP:delete-encrypt-keys}
    message:
      topic: ${KAFKA_MESSAGE_TOPIC:message-service}
      group: ${KAFKA_MESSAGE_GROUP:message-service}
    chat:
      topic: ${KAFKA_CHAT_TOPIC:chat-service}
      group: ${KAFKA_CHAT_GROUP:chat-service}
    encrypt-keys:
      topic: ${KAFKA_ENCRYPT_KEYS_TOPIC:encrypt-keys-service}
      group: ${KAFKA_ENCRYPT_KEYS_GROUP:encrypt-keys-service}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  application:
    name: mescat
  datasource:
    url: ${MESSAGE_DB_URL:jdbc:postgresql://localhost:5435/postgres}
    username: ${MESSAGE_DB_USERNAME:postgres}
    password: ${MESSAGE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: app-pool
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:15000}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      max-lifetime: ${DB_MAX_LIFETIME:1200000}

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  mvc:
    problemdetails:
      enabled: true
    format:
      date: iso
      date-time: iso
      time: iso

  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

  sql:
    init:
      mode: always
      schema-locations: classpath:start.sql

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF

app:
  max-active-key: ${MAX_ACTIVE_KEY:3}
  security:
    jwt:
      secret: ${JWT_SECRET:my-super-secret-key-my-super-secret-key-my-super-secret-key}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

services:
  user:
    base-url: ${USER_SERVICE_URL:http://localhost:8081}
  key-vault:
    base-url: ${KEY_VAULT_SERVICE_URL:http://localhost:8085}
